support reading scoop home from the config file
shilangyu/scoop-search pull request #30
Opened 2023-01-24 15:29 UTC by v1nh1shungry

The recent version doesn't require defining `SCOOP` to specify the custom install directory. Instead, it's now recommended to use `.\install.ps1 -ScoopDir 'D:\Applications\Scoop'` according to https://github.com/ScoopInstaller/Install#advanced-installation. In this way, scoop stores the root path in the config file which is typically 'C:\Users\foobar\.config\scoop\config.json`.

This patch adds support for reading scoop's config file to get the scoop's root path so users like me don't have to define `SCOOP` to have `scoop-search` works.

2023-01-25 00:52 UTC, shilangyu requested changes
For my reference:

- scoop installer decides about the root path using the param value but fallbacking to `$env:SCOOP` (https://github.com/ScoopInstaller/Install/blob/f1cf244456a4201a4ee3d1ad8cea2ac96e301198/install.ps1#L559)
- the config path is determined based off the XDG directory or just `~/.config` (https://github.com/ScoopInstaller/Install/blob/f1cf244456a4201a4ee3d1ad8cea2ac96e301198/install.ps1#L571)
- **BUT** once scoop is installed it gives higher priority to the `$env:SCOOP` variable over the config variable (https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/core.ps1#L1259)


So this PR LGTM. Except, if you could, please also read the XDG variable before reading the home directory, so that the behavior is the same as scoop's.

2023-01-25 00:52 UTC, shilangyu commented on main.go
> +		}
```suggestion
		if content, err := os.ReadFile(path); err == nil {
			var parser fastjson.Parser
			config, _ := parser.ParseBytes(content)
			res = string(config.GetStringBytes("root_path"))
		} else {
			res = home + "\\scoop"
		}
```

I think this inversion of condition will read better

2023-01-25 00:53 UTC, shilangyu commented
I think this also closes #28

2023-01-25 04:31 UTC, v1nh1shungry commented
Thanks for the review!

> Except, if you could, please also read the XDG variable before reading the home directory, so that the behavior is the same as scoop's.

I've considered it before. AFAIK the XDG variable is usually available in X, I thought scoop is mostly used in Windows. But you're right, let's keep the behavior the same as scoop's.

2023-01-25 09:19 UTC, shilangyu approved these changes

2023-01-25 09:21 UTC, merged

2023-01-25 09:27 UTC, shilangyu commented
Released as https://github.com/shilangyu/scoop-search/releases/tag/v1.3.0

2023-01-25 14:46 UTC, eidswe commented
@v1nh1shungry @shilangyu 
Unable to use scoop-search after update, encountered the same problem as #31

2023-01-25 14:46 UTC, eidswe commented
@v1nh1shungry @shilangyu 
Unable to use scoop-search after update, encountered the same problem as #31

2023-01-25 15:14 UTC, v1nh1shungry commented
Thanks for the report, @eidswe!

My guess is you have a config file which may be kind of `C:\Users\eidswe\.config\scoop\config.json`, but it doesn't have a field named `root_path`. Could you please check this? Thanks!

FYI, I check again the install script, and I find that when installed with `SCOOP` specified or the install directory is the default value, the installation won't write the root path.

2023-01-26 02:16 UTC, eidswe commented
Yes, config.json doesn't have a field named root_path, the issue has been fixed.Thank you